name: Backmerge main -> next

on:
    push:
        branches:
            - 'main'

jobs:
    backmerge:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - uses: everlytic/branch-merge@1.1.2
              with:
                  github_token: ${{ github.GH_NODE_TOKEN }}
                  source_ref: 'main'
                  target_branch: 'next'
                  commit_message_template: "Merge branch 'main' into 'next' [skip ci]"
